### ISSUE TITLE
Laravel pagination

### ISSUE THREAD

**Issue by threesquared** [Pod-Point/pod-point-ui-toolkit#118]
It would be handy if the toolkit could include styles for the standard Laravel pagination markup. This can be customised but the default markup which is designed for bootstrap is below. More info [here](https://laravel.com/docs/5.5/pagination#customizing-the-pagination-view).

```html
<ul class="pagination">
  <li class="disabled"><span>«</span></li>
  <li class="active"><span>1</span></li>
  <li><a href="?page=2">2</a></li>
  <li><a href="?page=2" rel="next">»</a></li>
</ul>
```

**Comment by matine** [comment]
Added to the toolkit https://pod-point.github.io/pod-point-ui-toolkit/pagination.html
