### ISSUE TITLE
Do not rely on "flexbox-grid-mixins" dependency

### ISSUE THREAD

**Issue by keanolane** [Pod-Point/pod-point-ui-toolkit#65]
This package has a bug we've identified regarding grid system, and an item in it with `white-space: nowrap` CSS rule, where the column will go over its max size.

I've opened a PR on their GitHub repository (https://github.com/thingsym/flexbox-grid-mixins/pull/3) but this package is maintained by only 1 dev and it's not maintained since 6 Oct 2016.

So we should do one of the following:

**1. We need to share this package**
Then we should fork this repository and use our fork as a dependency in the `ui-toolkit` instead.

**2. We just need this package in ui-toolkit**
Then we should copy the code from this mixin inside our `ui-tookit` repository.

-------------------------
***Sources:***
Github: https://github.com/thingsym/flexbox-grid-mixins
npm: https://www.npmjs.com/package/flexbox-grid-mixins

**Comment by matine** [comment]
This has been done
