### ISSUE TITLE
Automatically adding error classes to form group elements

### ISSUE THREAD

**Issue by joefhall** [Pod-Point/pod-point-ui-toolkit#77]
Currently the `form-fields` JS module adds an appropriately styled error message after a form field if there is an error with what the user has submitted.

It would be good if we could add further functionality so that when a field has an error, if the field is inside a container element (e.g. a `div`) with the `form__group` class set, then it also automatically adds the `form__group--error` class to that container element so that it is automatically styled too.

**Comment by mikefrancis** [comment]
I don't think we are using the `form-fields` any more so this behaviour needs to be handled in your `form-components` package.
